### PR TITLE
allow consumer to specify public key rather than generating it at runtime

### PR DESCRIPTION
**Pull request by ch-andrewrhyne**
See title

### CODE REVIEW

**Comment by ch-andrewrhyne** [comment]
Just wanted to note that this approach doesn't seem to work.  Would love advice on how to make this work correctly.

**Comment by mscdex** [comment]
Why is this necessary?

**Comment by ch-andrewrhyne** [comment]
The security team at my company wants control over how the public key is generated with a consistent algorithm to avoid security surface area spread.  If the algorithm requires a patch, we don't have to wait for third party components to adjust in how they generate certs.

**Comment by ch-andrewrhyne** [comment]
Bump

**Comment by mscdex** [comment]
The key handling has changed in v0.7.0, so there would need to be additional work to support this kind of feature.

However, I'm still not convinced supporting this is worthwhile. It will most likely cause confusion for end users (like it did when `publicKey` was a documented, supported option long before we had the ability to derive public keys from private keys). Currently I think it's already confusing enough for end users when supplying a private key for auth and 'publickey' being the actual name of the key-based authentication mechanism in the protocol.

Additionally, even if we were to support something like this, we would want to end up comparing our derived key to the separately provided public key to make sure they match. If they don't match, we would probably want to throw an exception. At that point it's hard to say what is wrong, is it a bug in the key parsing or is it the wrong, explicit public key?

**Pull request closed without merging**
