### PR TITLE
Only include necessary components in final module bundle by limiting files to /lib

### PR DESCRIPTION
**Pull request by mechinn**
Fixing #960 by only publishing lib not tests/examples

### CODE REVIEW

**Comment by mechinn** [comment]
It would be nice to also put this in v0.8.x and put 0.8.10 out

**Review by OmgImAlexis — APPROVED** [review]
LGTM should decrease the overall package size. 👍

**Comment by OmgImAlexis** [comment]
@mscdex could you give this a review when you have a chance?

**Comment by mscdex** [comment]
@OmgImAlexis I've already commented on the linked issue.

**Comment by OmgImAlexis** [comment]
That makes no sense. Users are needing to download extra data because of this personal choice.

**Comment by mscdex** [comment]
I'm not really interested in removing such files at this time.

**Comment by OmgImAlexis** [comment]
@mscdex care to give a valid reason for this? you're not getting any benefit from this and you're wasting dev's bandwidth.

**Pull request closed without merging**
